#############################################################################
# Makefile for building: can
# Generated by qmake (2.01a) (Qt 4.8.5) on: Mon Aug 19 06:54:26 2019
# Project:  can.pro
# Template: app
# Command: /usr/local/freescale/qt4.8.5/bin/qmake -spec /usr/local/freescale/qt4.8.5/mkspecs/qws/linux-imx6-g++ -o Makefile can.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-fsl-linux-gnueabi-gcc -lts
CXX           = arm-fsl-linux-gnueabi-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -O2 -march=armv7-a -mfpu=neon -DLINUX=1 -DEGL_API_FB=1 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -O2 -march=armv7-a -mfpu=neon -DLINUX=1 -DEGL_API_FB=1 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/freescale/qt4.8.5/mkspecs/qws/linux-imx6-g++ -I. -I/usr/local/freescale/qt4.8.5/include/QtCore -I/usr/local/freescale/qt4.8.5/include/QtNetwork -I/usr/local/freescale/qt4.8.5/include/QtGui -I/usr/local/freescale/qt4.8.5/include -I. -I. -I.
LINK          = arm-fsl-linux-gnueabi-g++ -lts
LFLAGS        = -W1,rpath=/work/imx6/rootfs/usr/lib -Wl,-O1 -Wl,-rpath,/usr/local/freescale/qt4.8.5/lib
LIBS          = $(SUBLIBS)  -L/usr/local/freescale/qt4.8.5/lib -lQtGui -L/usr/local/arm/tslib/lib -L/usr/local/freescale/qt4.8.5/lib -lQtNetwork -lQtCore -lpthread -lts 
AR            = arm-fsl-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /usr/local/freescale/qt4.8.5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-fsl-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		myinputpanel.cpp \
		myinputpanelcontext.cpp \
		thread.cpp \
		ccyclebuffer.cpp moc_mainwindow.cpp \
		moc_myinputpanel.cpp \
		moc_myinputpanelcontext.cpp \
		moc_thread.cpp \
		qrc_pic.cpp
OBJECTS       = main.o \
		mainwindow.o \
		myinputpanel.o \
		myinputpanelcontext.o \
		thread.o \
		ccyclebuffer.o \
		moc_mainwindow.o \
		moc_myinputpanel.o \
		moc_myinputpanelcontext.o \
		moc_thread.o \
		qrc_pic.o
DIST          = /usr/local/freescale/qt4.8.5/mkspecs/common/unix.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/linux.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/g++-unix.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/qws.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/qconfig.pri \
		/usr/local/freescale/qt4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/freescale/qt4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/release.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/default_post.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/shared.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/qt.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/moc.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/resources.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/uic.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/yacc.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/lex.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/include_source_dir.prf \
		can.pro
QMAKE_TARGET  = can
DESTDIR       = 
TARGET        = can

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_myinputpanelform.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: can.pro  /usr/local/freescale/qt4.8.5/mkspecs/qws/linux-imx6-g++/qmake.conf /usr/local/freescale/qt4.8.5/mkspecs/common/unix.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/linux.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/gcc-base.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/g++-base.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/g++-unix.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/common/qws.conf \
		/usr/local/freescale/qt4.8.5/mkspecs/qconfig.pri \
		/usr/local/freescale/qt4.8.5/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/freescale/qt4.8.5/mkspecs/features/qt_functions.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/qt_config.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/exclusive_builds.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/default_pre.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/release.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/default_post.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/shared.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/warn_on.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/qt.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/unix/thread.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/moc.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/resources.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/uic.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/yacc.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/lex.prf \
		/usr/local/freescale/qt4.8.5/mkspecs/features/include_source_dir.prf \
		/usr/local/freescale/qt4.8.5/lib/libQtGui.prl \
		/usr/local/freescale/qt4.8.5/lib/libQtNetwork.prl \
		/usr/local/freescale/qt4.8.5/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/freescale/qt4.8.5/mkspecs/qws/linux-imx6-g++ -o Makefile can.pro
/usr/local/freescale/qt4.8.5/mkspecs/common/unix.conf:
/usr/local/freescale/qt4.8.5/mkspecs/common/linux.conf:
/usr/local/freescale/qt4.8.5/mkspecs/common/gcc-base.conf:
/usr/local/freescale/qt4.8.5/mkspecs/common/gcc-base-unix.conf:
/usr/local/freescale/qt4.8.5/mkspecs/common/g++-base.conf:
/usr/local/freescale/qt4.8.5/mkspecs/common/g++-unix.conf:
/usr/local/freescale/qt4.8.5/mkspecs/common/qws.conf:
/usr/local/freescale/qt4.8.5/mkspecs/qconfig.pri:
/usr/local/freescale/qt4.8.5/mkspecs/modules/qt_webkit_version.pri:
/usr/local/freescale/qt4.8.5/mkspecs/features/qt_functions.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/qt_config.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/exclusive_builds.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/default_pre.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/release.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/default_post.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/shared.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/warn_on.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/qt.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/unix/thread.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/moc.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/resources.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/uic.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/yacc.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/lex.prf:
/usr/local/freescale/qt4.8.5/mkspecs/features/include_source_dir.prf:
/usr/local/freescale/qt4.8.5/lib/libQtGui.prl:
/usr/local/freescale/qt4.8.5/lib/libQtNetwork.prl:
/usr/local/freescale/qt4.8.5/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/freescale/qt4.8.5/mkspecs/qws/linux-imx6-g++ -o Makefile can.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/can1.0.0 || $(MKDIR) .tmp/can1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/can1.0.0/ && $(COPY_FILE) --parents mainwindow.h myinputpanel.h myinputpanelcontext.h thread.h ccyclebuffer.h .tmp/can1.0.0/ && $(COPY_FILE) --parents pic.qrc .tmp/can1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp myinputpanel.cpp myinputpanelcontext.cpp thread.cpp ccyclebuffer.cpp .tmp/can1.0.0/ && $(COPY_FILE) --parents mainwindow.ui myinputpanelform.ui .tmp/can1.0.0/ && (cd `dirname .tmp/can1.0.0` && $(TAR) can1.0.0.tar can1.0.0 && $(COMPRESS) can1.0.0.tar) && $(MOVE) `dirname .tmp/can1.0.0`/can1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/can1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_myinputpanel.cpp moc_myinputpanelcontext.cpp moc_thread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_myinputpanel.cpp moc_myinputpanelcontext.cpp moc_thread.cpp
moc_mainwindow.cpp: thread.h \
		ccyclebuffer.h \
		mainwindow.h
	/usr/local/freescale/qt4.8.5/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_myinputpanel.cpp: myinputpanel.h
	/usr/local/freescale/qt4.8.5/bin/moc $(DEFINES) $(INCPATH) myinputpanel.h -o moc_myinputpanel.cpp

moc_myinputpanelcontext.cpp: myinputpanelcontext.h
	/usr/local/freescale/qt4.8.5/bin/moc $(DEFINES) $(INCPATH) myinputpanelcontext.h -o moc_myinputpanelcontext.cpp

moc_thread.cpp: ccyclebuffer.h \
		thread.h
	/usr/local/freescale/qt4.8.5/bin/moc $(DEFINES) $(INCPATH) thread.h -o moc_thread.cpp

compiler_rcc_make_all: qrc_pic.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_pic.cpp
qrc_pic.cpp: pic.qrc \
		logo.png \
		picGray.png \
		picRed.png \
		picGreen.png
	/usr/local/freescale/qt4.8.5/bin/rcc -name pic pic.qrc -o qrc_pic.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_myinputpanelform.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_myinputpanelform.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/freescale/qt4.8.5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_myinputpanelform.h: myinputpanelform.ui
	/usr/local/freescale/qt4.8.5/bin/uic myinputpanelform.ui -o ui_myinputpanelform.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		thread.h \
		ccyclebuffer.h \
		myinputpanelcontext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		thread.h \
		ccyclebuffer.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

myinputpanel.o: myinputpanel.cpp myinputpanel.h \
		ui_myinputpanelform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myinputpanel.o myinputpanel.cpp

myinputpanelcontext.o: myinputpanelcontext.cpp myinputpanelcontext.h \
		myinputpanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myinputpanelcontext.o myinputpanelcontext.cpp

thread.o: thread.cpp thread.h \
		ccyclebuffer.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thread.o thread.cpp

ccyclebuffer.o: ccyclebuffer.cpp ccyclebuffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ccyclebuffer.o ccyclebuffer.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_myinputpanel.o: moc_myinputpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myinputpanel.o moc_myinputpanel.cpp

moc_myinputpanelcontext.o: moc_myinputpanelcontext.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myinputpanelcontext.o moc_myinputpanelcontext.cpp

moc_thread.o: moc_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thread.o moc_thread.cpp

qrc_pic.o: qrc_pic.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_pic.o qrc_pic.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

